[package]
name = "rust_leo_sim"
version = "0.1.0"
edition = "2021"

[dependencies]
sgp4 = "2.2.0"
serde_json = "1.0.139"
anyhow = "1.0.96"
pyo3 = "0.23.5"
rayon = "1.10.0"
satkit = "0.5.5"
nalgebra = "0.33.2"
